
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// SCSS

import '@/scss/base/reset.scss'
import Header from "@/components/Header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import localFont from 'next/font/local'

const Montserrat = localFont({
  src: './fonts/Montserrat/Montserrat-Medium.ttf', // Путь относительно layout.tsx
  display: 'swap', // Рекомендуется для улучшения восприятия загрузки
})


export const metadata: Metadata = {
  title: "Offer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
